/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A Sudachi Japanese dictionary */
export declare class Dictionary {
  /**
   * Load a dictionary from a compiled system dictionary file.
   *
   * @param dictPath - Optional path to the compiled system dictionary (.dic file). Uses default from config if omitted.
   * @param resourceDir - Optional path to the resource directory (containing char.def, unk.def, etc.)
   * @param configPath - Optional path to sudachi.json config file
   */
  constructor(dictPath?: string | undefined | null, resourceDir?: string | undefined | null, configPath?: string | undefined | null)
  /**
   * Create a reusable Tokenizer for this dictionary.
   *
   * @param mode - Split mode: "A" (short), "B" (middle), "C" (long, default)
   */
  create(mode?: string | undefined | null): Tokenizer
  /**
   * Tokenize Japanese text and return morphemes.
   *
   * @param text - Japanese text to analyze
   * @param mode - Split mode: "A" (short), "B" (middle), "C" (long, default)
   */
  tokenize(text: string, mode?: string | undefined | null): Array<Morpheme>
}

/** A Sudachi Japanese dictionary loaded from dictionary bytes. */
export declare class Dictionary_From_Byte {
  /**
   * Load a dictionary from dictionary bytes.
   *
   * @param dictBytes - Compiled system dictionary bytes (.dic file contents)
   * @param resourceDir - Optional path to the resource directory (containing char.def, unk.def, etc.)
   * @param configPath - Optional path to sudachi.json config file
   */
  constructor(dictBytes: Buffer, resourceDir?: string | undefined | null, configPath?: string | undefined | null)
  /**
   * Create a reusable Tokenizer for this dictionary.
   *
   * @param mode - Split mode: "A" (short), "B" (middle), "C" (long, default)
   */
  create(mode?: string | undefined | null): Tokenizer
  /**
   * Tokenize Japanese text and return morphemes.
   *
   * @param text - Japanese text to analyze
   * @param mode - Split mode: "A" (short), "B" (middle), "C" (long, default)
   */
  tokenize(text: string, mode?: string | undefined | null): Array<Morpheme>
}
export type DictionaryFromByte = Dictionary_From_Byte

/** A stateful tokenizer bound to a specific dictionary and split mode */
export declare class Tokenizer {
  /**
   * Tokenize Japanese text and return morphemes.
   *
   * @param text - Japanese text to analyze
   * @param mode - Override split mode for this call only
   */
  tokenize(text: string, mode?: string | undefined | null): Array<Morpheme>
  /** The split mode of this tokenizer ("A", "B", or "C") */
  get mode(): string
}

/** Return concrete config-related paths that `new Dictionary()` will use/try. */
export declare function dictionaryConfigPaths(dictPath?: string | undefined | null, resourceDir?: string | undefined | null, configPath?: string | undefined | null): DictionaryConfigPaths

export interface DictionaryConfigPaths {
  /** Requested config path. */
  requestedConfigPath?: string
  /** Actual config path used by this wrapper. Null when no config file is used. */
  actualConfigPath?: string
  /** Whether `actual_config_path` exists on the filesystem. */
  actualConfigExists?: boolean
  /** Candidate paths Sudachi will check for the system dictionary. */
  systemDictCandidates: Array<string>
  /** Candidate paths Sudachi will check for `char.def`. */
  charDefCandidates: Array<string>
}

/** A single morpheme (tokenization result unit) */
export interface Morpheme {
  /** Surface form — the substring of the original text */
  surface: string
  /** Part-of-speech components (6 elements: pos1, pos2, pos3, pos4, cType, cForm) */
  partOfSpeech: Array<string>
  /** Reading form in katakana (フリガナ) */
  readingForm: string
  /** Dictionary (lemma) form */
  dictionaryForm: string
  /** Normalized form */
  normalizedForm: string
  /** Whether this morpheme is out-of-vocabulary */
  isOov: boolean
  /** Begin byte offset in the original text */
  begin: number
  /** End byte offset in the original text */
  end: number
  /** Dictionary id (-1 for OOV words) */
  dictionaryId: number
}
